#!/usr/bin/perl

use FindBin;
die "You need to run 'git submodule update --init' to fetch the example requirements\n"
  unless -d "$FindBin::Bin/mojo/lib";

use lib "$FindBin::Bin/mojo/lib";
use lib "lib";

use Mojolicious::Lite;
use WSMud;

@ARGV = qw( daemon ) unless @ARGV;

my $world = WSMud::World->new();

get '/' => sub {
  my $self = shift;
  $self->render('index');
};

get '/player/:player_name' => sub {
  my $self = shift;  
  my $player_name = $self->param('player_name');
  
  $self->render('game', player_name => $player_name);
};

websocket '/mud/:player_name' => sub {
  my $self = shift;
  Mojo::IOLoop->stream($self->tx->connection)->timeout(300);
  my $player = WSMud::Player->new($self->param('player_name'), $world, $self);
};


app->start;

1;

__DATA__


@@ index.html.ep
Go to /player/:player_name to start playing.

@@ game.html.ep
    <html>
      <head>
        <title>WebSocket Mud Client</title>
        <script
          type="text/javascript"
          src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"
        ></script>
        <script type="text/javascript">
        $(function () {
          $('#msg').focus();

          var log = function (text) {
            $('#log').val( $('#log').val() + text + "\n");
          };
      
          var ws = new WebSocket('ws://localhost:3000/mud/<%= $player_name %>');
          ws.onopen = function () {
            log('Connection opened');
          };
          
          ws.onclose = function () {
            log('Connection closed');
          };
      
          ws.onmessage = function (msg) {
            var res = JSON.parse(msg.data);
            log(res.text); 
          };

          $('#msg').keydown(function (e) {
              if (e.keyCode == 13 && $('#msg').val()) {
                  ws.send($('#msg').val());
                  $('#msg').val('');
              }
            });
          });
        </script>
        <style type="text/css">
          textarea {
              width: 40em;
              height:10em;
          }
        </style>
      </head>
    <body>

    <h1><%= $player_name %></h1>
    
    <textarea id="log" readonly></textarea>
    <p><input type="text" id="msg" /></p>

    </body>
    </html>

