#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "lib";
use Mojolicious::Lite;
use WSMud;

@ARGV = qw( daemon ) unless @ARGV;

my $world = WSMud::World->new();

get '/' => sub {
    my $self = shift;
    $self->render('index');
};

get '/player/:player_name' => sub {
    my $self        = shift;
    my $player_name = $self->param('player_name');

    $self->render( 'game', player_name => $player_name );
};

websocket '/mud/:player_name' => sub {
    my $self = shift;
    Mojo::IOLoop->stream( $self->tx->connection )->timeout(300);
    my $player =
    WSMud::Player->new( $self->param('player_name'), $world, $self );
};

app->start;
